In [7]:
import pandas as pd

In [8]:
d1 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-01-metropolitan-street.csv")
d1.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.136387,51.589215,On or near Billet Road,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
1,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.140634,51.583427,On or near Rams Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.145888,51.593835,On or near Providence Place,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
4,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN

In [9]:
d2 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-02-metropolitan-street.csv")
d3 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-03-metropolitan-street.csv")
d4 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-04-metropolitan-street.csv")
d5 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-05-metropolitan-street.csv")
d6 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-06-metropolitan-street.csv")
d7 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-07-metropolitan-street.csv")
d8 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-08-metropolitan-street.csv")
d9 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-09-metropolitan-street.csv")
d10 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-10-metropolitan-street.csv")
d11 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-11-metropolitan-street.csv")
d12 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-12-metropolitan-street.csv")


d2018_1 = pd.concat([d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12])
d2018_1.to_csv('d2018_1.csv', index=False)

In [10]:
d2018_1 = pd.read_csv(r"C:\Users\User\d2018_1.csv")
d2018_1.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.136387,51.589215,On or near Billet Road,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
1,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.140634,51.583427,On or near Rams Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.145888,51.593835,On or near Providence Place,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
4,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN

In [11]:
print(d2018_1.shape)

(1054600, 12)

In [12]:
d13 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-01-city-of-london-street.csv")
d14 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-02-city-of-london-street.csv")
d15 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-03-city-of-london-street.csv")
d16 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-04-city-of-london-street.csv")
d17 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-05-city-of-london-street.csv")
d18 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-06-city-of-london-street.csv")
d19 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-07-city-of-london-street.csv")
d20 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-08-city-of-london-street.csv")
d21 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-09-city-of-london-street.csv")
d22 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-10-city-of-london-street.csv")
d23 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-11-city-of-london-street.csv")
d24 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2018-12-city-of-london-street.csv")

d2018_2 = pd.concat([d13, d14, d15, d16, d17, d18, d19, d20, d21, d22, d23, d24])
d2018_2.to_csv('d2018_2.csv', index=False)

In [13]:
d2018_2 = pd.read_csv(r"C:\Users\User\d2018_2.csv")
d2018_2.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,fb5980f681cc55836191d8537790a1629eb264de22acdf...,2018-01,City of London Police,City of London Police,-0.106453,51.518207,On or near Charterhouse Street,E01000916,Camden 027B,Other theft,Investigation complete; no suspect identified,NaN
1,NaN,2018-01,City of London Police,City of London Police,-0.114954,51.518632,On or near Brownlow Street,E01000914,Camden 028B,Anti-social behaviour,NaN,NaN
2,NaN,2018-01,City of London Police,City of London Police,-0.114954,51.518632,On or near Brownlow Street,E01000914,Camden 028B,Anti-social behaviour,NaN,NaN
3,60bf92023cede4382d088f3ef60c6536aac816744bd3cb...,2018-01,City of London Police,City of London Police,-0.111497,51.518226,On or near Pedestrian Subway,E01000914,Camden 028B,Burglary,Offender given community sentence,NaN
4,999497aac964c9cd1450eef9a88872a58b6ef2d09eaa99...,2018-01,City of London Police,City of London Police,-0.111962,51.518494,On or near Nightclub,E01000914,Camden 028B,Theft from the person,Investigation complete; no suspect identified,NaN

In [14]:
print(d2018_2.shape)

(8546, 12)

In [15]:
d2018_1 = pd.read_csv(r"C:\Users\User\d2018_1.csv")
d2018_2 = pd.read_csv(r"C:\Users\User\d2018_2.csv")

d2018_all = pd.concat([d2018_1, d2018_2])
d2018_all.to_csv('d2018_all.csv', index=False)

In [17]:
d2018_all = pd.read_csv(r"C:\Users\User\d2018_all.csv")

d2018_all.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.136387,51.589215,On or near Billet Road,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
1,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.140634,51.583427,On or near Rams Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.145888,51.593835,On or near Providence Place,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
4,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN

In [18]:
print(d2018_all.shape)

(1063146, 12)

In [19]:
d25 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-01-metropolitan-street.csv")
d26 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-02-metropolitan-street.csv")
d27 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-03-metropolitan-street.csv")
d28 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-04-metropolitan-street.csv")
d29 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-05-metropolitan-street.csv")
d30 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-06-metropolitan-street.csv")
d31 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-07-metropolitan-street.csv")
d32 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-08-metropolitan-street.csv")
d33 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-09-metropolitan-street.csv")
d34 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-10-metropolitan-street.csv")
d35 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-11-metropolitan-street.csv")
d36 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-12-metropolitan-street.csv")
d37 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-01-city-of-london-street.csv")
d38 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-02-city-of-london-street.csv")
d39 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-03-city-of-london-street.csv")
d40 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-04-city-of-london-street.csv")
d41 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-05-city-of-london-street.csv")
d42 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-06-city-of-london-street.csv")
d43 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-07-city-of-london-street.csv")
d44 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-08-city-of-london-street.csv")
d45 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-09-city-of-london-street.csv")
d46 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-10-city-of-london-street.csv")
d47 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-11-city-of-london-street.csv")
d48 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2019-12-city-of-london-street.csv")

d2019_all = pd.concat([d25, d26, d27, d28, d29, d30, d31, d32, d33, d34, d35, d36, d37, d38, d39, d40, d41, d42, d43, d44, d45, d46, d47, d48])
d2019_all.to_csv('d2019_all.csv', index=False)

In [20]:
d2019_all = pd.read_csv(r"C:\Users\User\d2019_all.csv")

d2019_all.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,a8977a2a4e14252420371eb993d52e4d0b8288a7c833e6...,2019-01,Metropolitan Police Service,Metropolitan Police Service,-0.709911,50.784615,On or near Rochester Way,E01031384,Arun 018E,Violence and sexual offences,Status update unavailable,NaN
1,NaN,2019-01,Metropolitan Police Service,Metropolitan Police Service,0.140192,51.582311,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,934e173f2bc2e1dd3a257b37939d8f97575d3eeb89ff0c...,2019-01,Metropolitan Police Service,Metropolitan Police Service,0.140192,51.582311,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Burglary,Status update unavailable,NaN
3,4f5b7e424bc78b1fb8c32e07da61176d2cbc5a3849d8e1...,2019-01,Metropolitan Police Service,Metropolitan Police Service,0.140634,51.583427,On or near Rams Grove,E01000027,Barking and Dagenham 001A,Burglary,Status update unavailable,NaN
4,53d960600a4a9f54b785f598af4c75bdef2f79bce1a41b...,2019-01,Metropolitan Police Service,Metropolitan Police Service,0.141143,51.590873,On or near Furze Farm Close,E01000027,Barking and Dagenham 001A,Drugs,Investigation complete; no suspect identified,NaN

In [21]:
print(d2019_all.shape)

(1118074, 12)

In [22]:
d49 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-01-metropolitan-street.csv")
d50 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-02-metropolitan-street.csv")
d51 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-03-metropolitan-street.csv")
d52 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-04-metropolitan-street.csv")
d53 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-05-metropolitan-street.csv")
d54 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-06-metropolitan-street.csv")
d55 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-07-metropolitan-street.csv")
d56 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-08-metropolitan-street.csv")
d57 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-09-metropolitan-street.csv")
d58 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-10-metropolitan-street.csv")
d59 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-11-metropolitan-street.csv")
d60 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-12-metropolitan-street.csv")
d61 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-01-city-of-london-street.csv")
d62 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-02-city-of-london-street.csv")
d63 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-03-city-of-london-street.csv")
d64 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-04-city-of-london-street.csv")
d65 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-05-city-of-london-street.csv")
d66 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-06-city-of-london-street.csv")
d67 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-07-city-of-london-street.csv")
d68 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-08-city-of-london-street.csv")
d69 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-09-city-of-london-street.csv")
d70 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-10-city-of-london-street.csv")
d71 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-11-city-of-london-street.csv")
d72 = pd.read_csv(r"C:\Users\User\Downloads\LONDON\2020-12-city-of-london-street.csv")

d2020_all = pd.concat([d49, d50, d51, d52, d53, d54, d55, d56, d57, d58, d59, d60, d61, d62, d63, d64, d65, d66, d67, d68, d69, d70, d71, d72])
d2020_all.to_csv('d2020_all.csv', index=False)

In [23]:
d2020_all = pd.read_csv(r"C:\Users\User\d2020_all.csv")

d2020_all.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,24c2b43c34c7cd6ef847d69fbb042c9c730b1eebe95c52...,2020-01,Metropolitan Police Service,Metropolitan Police Service,-0.539301,50.817200,On or near Highdown Drive,E01031469,Arun 009F,Other theft,Status update unavailable,NaN
1,NaN,2020-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,NaN,2020-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,NaN,2020-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
4,NaN,2020-01,Metropolitan Police Service,Metropolitan Police Service,0.141143,51.590873,On or near Furze Farm Close,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN

In [24]:
print(d2020_all.shape)

(1187847, 12)

In [28]:
d2018_all = pd.read_csv(r"C:\Users\User\d2018_all.csv")
d2019_all = pd.read_csv(r"C:\Users\User\d2019_all.csv")
d2020_all = pd.read_csv(r"C:\Users\User\d2020_all.csv")


d2018_to_2020 = pd.concat([d2018_all, d2019_all, d2020_all])
d2018_to_2020.to_csv('d2018_to_2020.csv', index=False)

In [29]:
d2018_to_2020 = pd.read_csv(r"C:\Users\User\d2018_to_2020.csv")

d2018_to_2020.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.136387,51.589215,On or near Billet Road,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
1,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.140634,51.583427,On or near Rams Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.145888,51.593835,On or near Providence Place,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
4,NaN,2018-01,Metropolitan Police Service,Metropolitan Police Service,0.137065,51.583672,On or near Police Station,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN

In [27]:
print(d2018_to_2020.shape)

(3369067, 12)

In [32]:
d73 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-01-metropolitan-street.csv")
d74 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-02-metropolitan-street.csv")
d75 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-03-metropolitan-street.csv")
d76 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-04-metropolitan-street.csv")
d77 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-05-metropolitan-street.csv")
d78 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-06-metropolitan-street.csv")
d79 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-07-metropolitan-street.csv")
d80 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-08-metropolitan-street.csv")
d81 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-09-metropolitan-street.csv")
d82 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-01-city-of-london-street.csv")
d83 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-02-city-of-london-street.csv")
d84 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-03-city-of-london-street.csv")
d85 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-04-city-of-london-street.csv")
d86 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-05-city-of-london-street.csv")
d87 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-06-city-of-london-street.csv")
d88 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-07-city-of-london-street.csv")
d89 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-08-city-of-london-street.csv")
d90 = pd.read_csv(r"C:\Users\User\Downloads\2021_LONDON\2021-09-city-of-london-street.csv")

d2021 = pd.concat([d73, d74, d75, d76, d77, d78, d79, d80, d81, d82, d83, d84, d85, d86, d87, d88, d89, d90])
d2021.to_csv('d2021.csv', index=False)

In [33]:
d2021 = pd.read_csv(r"C:\Users\User\d2021.csv")

d2021.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,d7184bda9365b4c4af9838f13e1daa24e98c0aa40eab39...,2021-01,Metropolitan Police Service,Metropolitan Police Service,0.880386,51.219190,On or near Buck Street,E01023989,Ashford 002C,Violence and sexual offences,Status update unavailable,NaN
1,NaN,2021-01,Metropolitan Police Service,Metropolitan Police Service,0.140192,51.582311,On or near Hatch Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
2,NaN,2021-01,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
3,NaN,2021-01,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN
4,NaN,2021-01,Metropolitan Police Service,Metropolitan Police Service,0.134947,51.588063,On or near Mead Grove,E01000027,Barking and Dagenham 001A,Anti-social behaviour,NaN,NaN

In [10]:
# sort London 2018, 2019 and 2020 street crime data by 'Month' and 'Reported by'

import pandas as pd

london2018_2020 = pd.read_csv(r"C:\Users\User\d2018_to_2020.csv")

# display original unsorted data
print("\nBefore sorting:")
print(london2018_2020)

# sort data
london2018_2020.sort_values(["Month", "Reported by"],
                            axis=0,
                            ascending=[True, True],
                            inplace=True)

# display sorted data
print("\nAfter sorting:")
print(london2018_2020)

Before sorting:
                                                  Crime ID    Month  \
0                                                      NaN  2018-01
1                                                      NaN  2018-01
2                                                      NaN  2018-01
3                                                      NaN  2018-01
4                                                      NaN  2018-01
...                                                    ...      ...
3369062  47eae7581e8cb1421e9ccbf031d83e8c0fd33fef32c7bc...  2020-12
3369063  dc40f1c00c525d21c042d520588b59fbe533b512b3e95d...  2020-12
3369064  8730c868be02f193fd278c00abc307ed126dffe85c41f1...  2020-12
3369065  de00402738b9b33ab423cba4c86af9847865ff9827c826...  2020-12
3369066  aeafcefd70fdae826b7ac4bfc1ed7580b115c32f8dc0b8...  2020-12

                         Reported by                 Falls within  Longitude  \
0        Metropolitan Police Service  Metropolitan Police Service   0.136387
1        Metropolitan Police Service  Metropolitan Police Service   0.140634
2        Metropolitan Police Service  Metropolitan Police Service   0.145888
3        Metropolitan Police Service  Metropolitan Police Service   0.137065
4        Metropolitan Police Service  Metropolitan Police Service   0.137065
...                              ...                          ...        ...
3369062        City of London Police        City of London Police        NaN
3369063        City of London Police        City of London Police        NaN
3369064        City of London Police        City of London Police        NaN
3369065        City of London Police        City of London Police        NaN
3369066        City of London Police        City of London Police        NaN

          Latitude                     Location  LSOA code  \
0        51.589215       On or near Billet Road  E01000027
1        51.583427        On or near Rams Grove  E01000027
2        51.593835  On or near Providence Place  E01000027
3        51.583672    On or near Police Station  E01000027
4        51.583672    On or near Police Station  E01000027
...            ...                          ...        ...
3369062        NaN                  No Location        NaN
3369063        NaN                  No Location        NaN
3369064        NaN                  No Location        NaN
3369065        NaN                  No Location        NaN
3369066        NaN                  No Location        NaN

                         LSOA name             Crime type  \
0        Barking and Dagenham 001A  Anti-social behaviour
1        Barking and Dagenham 001A  Anti-social behaviour
2        Barking and Dagenham 001A  Anti-social behaviour
3        Barking and Dagenham 001A  Anti-social behaviour
4        Barking and Dagenham 001A  Anti-social behaviour
...                            ...                    ...
3369062                        NaN            Other crime
3369063                        NaN            Other crime
3369064                        NaN            Other crime
3369065                        NaN            Other crime
3369066                        NaN            Other crime

                              Last outcome category  Context
0                                               NaN      NaN
1                                               NaN      NaN
2                                               NaN      NaN
3                                               NaN      NaN
4                                               NaN      NaN
...                                             ...      ...
3369062  Action to be taken by another organisation      NaN
3369063                 Unable to prosecute suspect      NaN
3369064                    Offender given a caution      NaN
3369065                   Status update unavailable      NaN
3369066                 Unable to prosecute suspect      NaN

[3369067 rows x 12 columns]

After sorting:
                                                  Crime ID    Month  \
1054600  fb5980f681cc55836191d8537790a1629eb264de22acdf...  2018-01
1054601                                                NaN  2018-01
1054602                                                NaN  2018-01
1054603  60bf92023cede4382d088f3ef60c6536aac816744bd3cb...  2018-01
1054604  999497aac964c9cd1450eef9a88872a58b6ef2d09eaa99...  2018-01
...                                                    ...      ...
3363137  826ceb8d3d2f79363e852449055994f5a8fec53b938fd7...  2020-12
3363138  54ce60d717f01752c5ff44f870e07a503e3fbeaae0b91e...  2020-12
3363139  826ceb8d3d2f79363e852449055994f5a8fec53b938fd7...  2020-12
3363140  580fdc2edfe26a09392ab6b9128732ba0c7cd05695387a...  2020-12
3363141  2730906a962972bed3589463c9be9dbb8ee8e594b779a3...  2020-12

                         Reported by                 Falls within  Longitude  \
1054600        City of London Police        City of London Police  -0.106453
1054601        City of London Police        City of London Police  -0.114954
1054602        City of London Police        City of London Police  -0.114954
1054603        City of London Police        City of London Police  -0.111497
1054604        City of London Police        City of London Police  -0.111962
...                              ...                          ...        ...
3363137  Metropolitan Police Service  Metropolitan Police Service        NaN
3363138  Metropolitan Police Service  Metropolitan Police Service        NaN
3363139  Metropolitan Police Service  Metropolitan Police Service        NaN
3363140  Metropolitan Police Service  Metropolitan Police Service        NaN
3363141  Metropolitan Police Service  Metropolitan Police Service        NaN

          Latitude                        Location  LSOA code    LSOA name  \
1054600  51.518207  On or near Charterhouse Street  E01000916  Camden 027B
1054601  51.518632      On or near Brownlow Street  E01000914  Camden 028B
1054602  51.518632      On or near Brownlow Street  E01000914  Camden 028B
1054603  51.518226    On or near Pedestrian Subway  E01000914  Camden 028B
1054604  51.518494            On or near Nightclub  E01000914  Camden 028B
...            ...                             ...        ...          ...
3363137        NaN                     No Location        NaN          NaN
3363138        NaN                     No Location        NaN          NaN
3363139        NaN                     No Location        NaN          NaN
3363140        NaN                     No Location        NaN          NaN
3363141        NaN                     No Location        NaN          NaN

                           Crime type  \
1054600                   Other theft
1054601         Anti-social behaviour
1054602         Anti-social behaviour
1054603                      Burglary
1054604         Theft from the person
...                               ...
3363137  Violence and sexual offences
3363138                   Other crime
3363139                   Other crime
3363140                   Other crime
3363141                   Other crime

                                 Last outcome category  Context
1054600  Investigation complete; no suspect identified      NaN
1054601                                            NaN      NaN
1054602                                            NaN      NaN
1054603              Offender given community sentence      NaN
1054604  Investigation complete; no suspect identified      NaN
...                                                ...      ...
3363137                      Status update unavailable      NaN
3363138  Investigation complete; no suspect identified      NaN
3363139                      Status update unavailable      NaN
3363140                       Offender given a caution      NaN
3363141  Investigation complete; no suspect identified      NaN

[3369067 rows x 12 columns]

In [11]:
# save sorted data

london2018_2020.to_csv('london2018_2020.csv', index=False)

In [12]:
# read sorted data

london2018_2020 = pd.read_csv(r"C:\Users\User\london2018_2020.csv")

london2018_2020.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,fb5980f681cc55836191d8537790a1629eb264de22acdf...,2018-01,City of London Police,City of London Police,-0.106453,51.518207,On or near Charterhouse Street,E01000916,Camden 027B,Other theft,Investigation complete; no suspect identified,NaN
1,NaN,2018-01,City of London Police,City of London Police,-0.114954,51.518632,On or near Brownlow Street,E01000914,Camden 028B,Anti-social behaviour,NaN,NaN
2,NaN,2018-01,City of London Police,City of London Police,-0.114954,51.518632,On or near Brownlow Street,E01000914,Camden 028B,Anti-social behaviour,NaN,NaN
3,60bf92023cede4382d088f3ef60c6536aac816744bd3cb...,2018-01,City of London Police,City of London Police,-0.111497,51.518226,On or near Pedestrian Subway,E01000914,Camden 028B,Burglary,Offender given community sentence,NaN
4,999497aac964c9cd1450eef9a88872a58b6ef2d09eaa99...,2018-01,City of London Police,City of London Police,-0.111962,51.518494,On or near Nightclub,E01000914,Camden 028B,Theft from the person,Investigation complete; no suspect identified,NaN

In [13]:
print(london2018_2020.shape)

(3369067, 12)

In [15]:
# sort London 2021 street crime data by 'Month' and 'Reported by'

london2021 = pd.read_csv(r"C:\Users\User\d2021.csv")

# display original unsorted data
print("\nBefore sorting:")
print(london2021)

# sort data
london2021.sort_values(["Month", "Reported by"],
                            axis=0,
                            ascending=[True, True],
                            inplace=True)

# display sorted data
print("\nAfter sorting:")
print(london2021)

Before sorting:
                                                 Crime ID    Month  \
0       d7184bda9365b4c4af9838f13e1daa24e98c0aa40eab39...  2021-01
1                                                     NaN  2021-01
2                                                     NaN  2021-01
3                                                     NaN  2021-01
4                                                     NaN  2021-01
...                                                   ...      ...
810418  19a65a0d881580eae20315f534a1a075402b22b9c21a11...  2021-09
810419  c8861249bbb5643aa7df17a929630f7b78dbcb49e5ad45...  2021-09
810420  7ef1988256672bdbdfffde187c6c61b7c9fb50b027fffa...  2021-09
810421  c6c1cf87acc2993117896f5be9e04c5021eed5ba969105...  2021-09
810422  ba016a3eb94cc50a6f98c7a66f424148f258029a1a9c81...  2021-09

                        Reported by                 Falls within  Longitude  \
0       Metropolitan Police Service  Metropolitan Police Service   0.880386
1       Metropolitan Police Service  Metropolitan Police Service   0.140192
2       Metropolitan Police Service  Metropolitan Police Service   0.134947
3       Metropolitan Police Service  Metropolitan Police Service   0.134947
4       Metropolitan Police Service  Metropolitan Police Service   0.134947
...                             ...                          ...        ...
810418        City of London Police        City of London Police        NaN
810419        City of London Police        City of London Police        NaN
810420        City of London Police        City of London Police        NaN
810421        City of London Police        City of London Police        NaN
810422        City of London Police        City of London Police        NaN

         Latitude                Location  LSOA code  \
0       51.219190  On or near Buck Street  E01023989
1       51.582311  On or near Hatch Grove  E01000027
2       51.588063   On or near Mead Grove  E01000027
3       51.588063   On or near Mead Grove  E01000027
4       51.588063   On or near Mead Grove  E01000027
...           ...                     ...        ...
810418        NaN             No Location        NaN
810419        NaN             No Location        NaN
810420        NaN             No Location        NaN
810421        NaN             No Location        NaN
810422        NaN             No Location        NaN

                        LSOA name                    Crime type  \
0                    Ashford 002C  Violence and sexual offences
1       Barking and Dagenham 001A         Anti-social behaviour
2       Barking and Dagenham 001A         Anti-social behaviour
3       Barking and Dagenham 001A         Anti-social behaviour
4       Barking and Dagenham 001A         Anti-social behaviour
...                           ...                           ...
810418                        NaN                   Other crime
810419                        NaN                   Other crime
810420                        NaN                   Other crime
810421                        NaN                   Other crime
810422                        NaN                   Other crime

            Last outcome category  Context
0       Status update unavailable      NaN
1                             NaN      NaN
2                             NaN      NaN
3                             NaN      NaN
4                             NaN      NaN
...                           ...      ...
810418        Under investigation      NaN
810419        Under investigation      NaN
810420        Under investigation      NaN
810421        Under investigation      NaN
810422        Under investigation      NaN

[810423 rows x 12 columns]

After sorting:
                                                 Crime ID    Month  \
806165                                                NaN  2021-01
806166                                                NaN  2021-01
806167  19f06058a3b0aa0e79eabc017b48862f2a6a06645b2f5c...  2021-01
806168  455f0a5e2aa0b0998be8adce21c42e362d85cb5cd0e31a...  2021-01
806169  fe0819e6a82093685a947e32f6b085c727d717244f9e79...  2021-01
...                                                   ...      ...
806160  a4ce0d323fd2eb431c8ef4b51e88fe7cfd2d77b62d1300...  2021-09
806161  6d28a027e9145d8240dc8b8a89660576e17402d41f9560...  2021-09
806162  1dbe537f3efe052823f5ee0a199002c91ceb9e1da764dc...  2021-09
806163  f008e359543fb3c4cdf88c244e0139ee2b9267839b1360...  2021-09
806164  36237c5e7a39e6a97d67181c11f479cb86b6ff67a8f7af...  2021-09

                        Reported by                 Falls within  Longitude  \
806165        City of London Police        City of London Police  -0.098572
806166        City of London Police        City of London Police  -0.097601
806167        City of London Police        City of London Police  -0.098572
806168        City of London Police        City of London Police  -0.097334
806169        City of London Police        City of London Police  -0.097601
...                             ...                          ...        ...
806160  Metropolitan Police Service  Metropolitan Police Service        NaN
806161  Metropolitan Police Service  Metropolitan Police Service        NaN
806162  Metropolitan Police Service  Metropolitan Police Service        NaN
806163  Metropolitan Police Service  Metropolitan Police Service        NaN
806164  Metropolitan Police Service  Metropolitan Police Service        NaN

         Latitude                       Location  LSOA code  \
806165  51.516767  On or near King Edward Street  E01000001
806166  51.520699   On or near Carthusian Street  E01000001
806167  51.516767  On or near King Edward Street  E01000001
806168  51.521567         On or near Fann Street  E01000001
806169  51.520699   On or near Carthusian Street  E01000001
...           ...                            ...        ...
806160        NaN                    No Location        NaN
806161        NaN                    No Location        NaN
806162        NaN                    No Location        NaN
806163        NaN                    No Location        NaN
806164        NaN                    No Location        NaN

                  LSOA name             Crime type  \
806165  City of London 001A  Anti-social behaviour
806166  City of London 001A  Anti-social behaviour
806167  City of London 001A            Other theft
806168  City of London 001A            Other theft
806169  City of London 001A            Shoplifting
...                     ...                    ...
806160                  NaN            Other crime
806161                  NaN            Other crime
806162                  NaN            Other crime
806163                  NaN            Other crime
806164                  NaN            Other crime

                                Last outcome category  Context
806165                                            NaN      NaN
806166                                            NaN      NaN
806167  Investigation complete; no suspect identified      NaN
806168  Investigation complete; no suspect identified      NaN
806169                      Status update unavailable      NaN
...                                               ...      ...
806160                            Under investigation      NaN
806161                            Under investigation      NaN
806162                            Under investigation      NaN
806163  Investigation complete; no suspect identified      NaN
806164                            Under investigation      NaN

[810423 rows x 12 columns]

In [17]:
# save sorted data

london2021.to_csv('london2021.csv', index=False)

In [18]:
# read sorted data

london2021 = pd.read_csv(r"C:\Users\User\london2021.csv")

london2021.head()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
0,NaN,2021-01,City of London Police,City of London Police,-0.098572,51.516767,On or near King Edward Street,E01000001,City of London 001A,Anti-social behaviour,NaN,NaN
1,NaN,2021-01,City of London Police,City of London Police,-0.097601,51.520699,On or near Carthusian Street,E01000001,City of London 001A,Anti-social behaviour,NaN,NaN
2,19f06058a3b0aa0e79eabc017b48862f2a6a06645b2f5c...,2021-01,City of London Police,City of London Police,-0.098572,51.516767,On or near King Edward Street,E01000001,City of London 001A,Other theft,Investigation complete; no suspect identified,NaN
3,455f0a5e2aa0b0998be8adce21c42e362d85cb5cd0e31a...,2021-01,City of London Police,City of London Police,-0.097334,51.521567,On or near Fann Street,E01000001,City of London 001A,Other theft,Investigation complete; no suspect identified,NaN
4,fe0819e6a82093685a947e32f6b085c727d717244f9e79...,2021-01,City of London Police,City of London Police,-0.097601,51.520699,On or near Carthusian Street,E01000001,City of London 001A,Shoplifting,Status update unavailable,NaN

In [19]:
print(london2021.shape)

(810423, 12)

In [2]:
import pandas as pd

london2021 = pd.read_csv(r"C:\Users\User\london2021.csv")

london2021.tail()

,Crime ID,Month,Reported by,Falls within,Longitude,Latitude,Location,LSOA code,LSOA name,Crime type,Last outcome category,Context
810418,a4ce0d323fd2eb431c8ef4b51e88fe7cfd2d77b62d1300...,2021-09,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
810419,6d28a027e9145d8240dc8b8a89660576e17402d41f9560...,2021-09,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
810420,1dbe537f3efe052823f5ee0a199002c91ceb9e1da764dc...,2021-09,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN
810421,f008e359543fb3c4cdf88c244e0139ee2b9267839b1360...,2021-09,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Investigation complete; no suspect identified,NaN
810422,36237c5e7a39e6a97d67181c11f479cb86b6ff67a8f7af...,2021-09,Metropolitan Police Service,Metropolitan Police Service,NaN,NaN,No Location,NaN,NaN,Other crime,Under investigation,NaN